### ISSUE TITLE
Update ELRS firmware

### ISSUE THREAD

**Issue by benedikt-bartscher** [mikeneiderhauser/CRSFJoystick#10]
Hey @mikeneiderhauser, thanks you for your awesome work! Is there a way to update the ELRS receiver firmware? Or is it currenty always in USB HID mode?

**Comment by benedikt-bartscher** [comment]
Thanks for your answer. Sadly some ELRS receivers don't have wifi (868mhz ones).
Couldn't we just introduce a boot delay in which the user can press for example a button to start in FW update mode?
Betaflight allows updating elrs receivers with serial passtrough, i used it many times, works great. Did you try this https://docs.arduino.cc/built-in-examples/communication/SerialPassthrough ?

**Comment by mikeneiderhauser** [comment]
You can't do just native serial pass through (at least on the ESP based RX's, haven't tried the STM based RX's) as the boot loader does dynamic baud rates for programming.  I've tried dedicated bridge / serial pass through firmware that is supposed to do dynamic baud without success.

**Comment by countofkrakow** [comment]
Just submitted a PR for this

**Comment by mikeneiderhauser** [comment]
PR merged, elrs passthrough flashing is now functional
