### ISSUE TITLE
Add instructions for Seeed XIAO 2040

### ISSUE THREAD

**Issue by benedikt-bartscher** [mikeneiderhauser/CRSFJoystick#11]
Compiling with Arduino Mbed OS RP2040 Boards -> Raspberry PI pico works fine, but uploading fails.
I tried compiling with different board definitions for the Seeed 2040 but i always get this error while compiling:
```
/home/bb/dev/CRSFJoystick/Sketchbook/libraries/PicoGamepad/PicoGamepad.h:21:10: fatal error: PluggableUSBHID.h: No such file or directory
```

**Comment by mikeneiderhauser** [comment]
IIRC you still target the Pi pico not the seeed 2040.  Change the define selection at the top of the sketch and it should just work (at least how i've done it in the past).

**Comment by benedikt-bartscher** [comment]
Yes that's what i tried first, compilation works finde, but uploading always fails with this message (i tried in normal and bootloader mode):
```
Beim Hochladen des Sketches ist ein Fehler aufgetreten
```

However uploading an empty sketch via the Seeed XIAO target works fine.

**Comment by sk8board** [comment]
I noticed the Seeed XIAO 2040 only has UART0 (Serial1) but the `main.cpp` file calls for Serial2 (UART1).

![Serial2 defined](https://github.com/mikeneiderhauser/CRSFJoystick/assets/96895142/fc8a4617-f540-4dd3-8d63-38c79ae6fd36)

Is the problem from the incorrect UART being used for Seeed XIAO 2040?
