### ISSUE TITLE
Fpv Exchange is down

### ISSUE THREAD

**Issue by erockman95** [mikeneiderhauser/CRSFJoystick#15]
It seems that fpvexchange.com is down. Is there another way to buy the carrier board and/or premade units?

**Comment by mikeneiderhauser** [comment]
Yea, unfortunately it looks like FPVexchange is down for good.  Message me on discord (HouseFPV) and I'll see if I have anything left here in stock and we can get something working to send to you.

**Comment by erockman95** [comment]
Hey Mike,

Sorry I missed your email. In the meantime I was able to find a
crsf joystick2.0 online and bought it. Only problem is, I'm having trouble
programming it. Any chance you'd be able to help a brotha out? Also, tried
finding you on discord, but for some reason I can't find anything. Do you
have a direct link or your usercode or something that'd I'd be able to use
to get in touch with you? Thanks again.

**Comment by erockman95** [comment]
Nevermind, was making a dumb mistake. I got it. Preciate all the effort you guys put in to this project! I'll be on the look out in case you do anything else in the future. And I'd deff still want to join your discord, so if you can get me a way to join thatd be dope. Take it easy Mike
