### ISSUE TITLE
Support for more buttons

### ISSUE THREAD

**Issue by relaxibus** [mikeneiderhauser/CRSFJoystick#16]
Hi, awesome project! Do you plan to add more buttons? Multiple buttons can be mapped on a single channel using different pwm values.

I made a XIAO carrier board, could this be added to your support? I‘m not a coder, but can send you a board.

**Comment by mikeneiderhauser** [comment]
Hi Relaxibus, If you contact me on Discord (HouseFPV) we can work together to see what you want multiple buttons wise as well as getting your carrier board in for XIAO.

**Comment by relaxibus** [comment]
Ok!

**Comment by mikeneiderhauser** [comment]
Unfortunately button mapping isn't a one size fits all for everyone.  You can add more buttons to the map by modifying the configuration here

https://github.com/mikeneiderhauser/CRSFJoystick/blob/master/Sketchbook/CRSF_Joystick/calibration.h#L47

If you would like to propose some better defaults than the stock 8 buttons please let me know!

**Comment by relaxibus** [comment]
ok, thanks :-)
