### ISSUE TITLE
Add pin info in readme

### ISSUE THREAD

**Issue by RobertoD91** [mikeneiderhauser/CRSFJoystick#21]
Hi, thank you for this amazing work. It might be a good idea to add the default TX and RX pins in the README.

Something like
| Raspberry Pico      | CRSF Receiver |
| ----------- | ----------- |
| 4      | RX       |
| 5   | TX        |

![IMG_3062 - dimensioni grandi](https://github.com/mikeneiderhauser/CRSFJoystick/assets/298514/ad8d2081-1762-42f3-81cc-76a895690a80)

**Comment by mikeneiderhauser** [comment]
Added a pin section to the DIY hardware heading in the README.  
https://github.com/mikeneiderhauser/CRSFJoystick#diy-hardware

Other pin defs can also be found in the board_defs.h file

Thanks for the feedback!
