### ISSUE TITLE
Taking it a step further!

### ISSUE THREAD

**Issue by naggie** [mikeneiderhauser/CRSFJoystick#28]
Thanks @mikeneiderhauser for this project. It works flawlessly and I've built a few modules so far.

This weekend I took it further and did the same for my FPV goggles! You might want to check it out https://calbryant.uk/blog/fpv-drone-simulator-9000/ and maybe link it as a suggestion or photos if you like.

![image](https://github.com/user-attachments/assets/b8d90bad-c763-4096-aad0-126fd13680fa)

Cal

**Comment by mikeneiderhauser** [comment]
Nice write up. Thanks for the link.
