### ISSUE TITLE
PCB file does not include v1.1

### ISSUE THREAD

**Issue by L1cardo** [mikeneiderhauser/CRSFJoystick#4]
Hi, the pcb file you privided does not include 1.1 version. Can you upload them please?
Thanks!
![image](https://user-images.githubusercontent.com/33802186/201103736-7e42706f-21ef-4ac7-b429-b56fdb4d9ff3.png)

**Comment by mikeneiderhauser** [comment]
Please check here.  Not the pcb files, but a gerber bundle you can directly upload to fab
https://github.com/mikeneiderhauser/CRSFJoystick/tree/master/hardware/kicad/CRSFJoystick/output/Rev1.1

**Comment by L1cardo** [comment]
I know this.
In China, there is a PCB manufacturer where you can get PCBs for free only if you have the origin files.
