### ISSUE TITLE
pitch not working on ubuntu 

### ISSUE THREAD

**Issue by kenken64** [mikeneiderhauser/CRSFJoystick#6]
axis 0 not working when i push the pitch forward it stays on 0 , after calibrate also useless

**Comment by mikeneiderhauser** [comment]
I've tested this on ubuntu.  Can you please provide more info?
What MCU are you using?
Did you make boards?
Did you modify the pi pico code, if so, what were the modifications?
ELRS Version?
Ubuntu Version?
